### ISSUE TITLE
ToDo's für MVP

### ISSUE THREAD

**Issue by felixguendling** [motis-project/icc#7]
- [x] Real-time support
- [x] Multi threading (for now only with asio, but ctx or boost::fiber is possible)
- [x] Multi dataset support (src index / tag prefix)
- [x] `motis import` -> standalone data folder
- [x] Zuglauf API
- [x] Abf&Ank Tabelle API
